"""Currency mapping utilities for default country-based currency assignment"""

def get_country_currency_mapping():
    """Return mapping of countries to their default currencies"""
    return {
        'United States': 'USD',
        'Canada': 'CAD',
        'United Kingdom': 'GBP',
        'Australia': 'AUD',
        'Germany': 'EUR',
        'France': 'EUR',
        'Italy': 'EUR',
        'Spain': 'EUR',
        'Netherlands': 'EUR',
        'Japan': 'JPY',
        'China': 'CNY',
        'India': 'INR',
        'Nepal': 'NPR',
        'Pakistan': 'PKR',
        'Bangladesh': 'BDT',
        'Sri Lanka': 'LKR',
        'South Korea': 'KRW',
        'Singapore': 'SGD',
        'Thailand': 'THB',
        'Malaysia': 'MYR',
        'Indonesia': 'IDR',
        'Philippines': 'PHP',
        'Vietnam': 'VND',
        'Brazil': 'BRL',
        'Mexico': 'MXN',
        'Argentina': 'ARS',
        'Chile': 'CLP',
        'Colombia': 'COP',
        'South Africa': 'ZAR',
        'Nigeria': 'NGN',
        'Egypt': 'EGP',
        'United Arab Emirates': 'AED',
        'Saudi Arabia': 'SAR',
        'Switzerland': 'CHF',
        'Norway': 'NOK',
        'Sweden': 'SEK',
        'Denmark': 'DKK',
        'Poland': 'PLN',
        'Russia': 'RUB',
    }
